server:
  name: "amusing-x/charon"
  httpServer:
    addr: :10004
  grpcServer:
    network: tcp
    address: :20004
mysql:
  plutodb:
    db: plutodb
    user: klooktest
    password: sees7&chanting
    host: localhost
    port: 3306
    protocol: tcp
    maxLifeTime: 3600
    maxOpenConns: 100
    maxIdleConns: 10
redis:
  redis1:
    addr: 127.0.0.1:6379
    dbNo: 1