server:
  name: "amusing-x/callisto"
  httpServer:
    addr: :10002
  grpcServer:
    network: tcp
    address: :20002
mysql:
  plutodb:
    db: plutodb
    user: test111
    password: pass123456
    host: localhost
    port: 3306
    protocol: tcp
    maxLifeTime: 3600
    maxOpenConns: 100
    maxIdleConns: 10
redis:
  redis1:
    addr: 127.0.0.1:6379
    dbNo: 1
session:
  redisStrore:
    redisAddr: localhost:6379
    redisNo: 2
    keyPrefix: uid