server:
  name: "amusing-x/pluto"
  httpServer:
    addr: :10005
  grpcServer:
    network: tcp
    address: :20005
mysql:
  plutodb:
    db: plutodb
    user: test111
    password: pass123456
    host: localhost
    port: 3306
    protocol: tcp
    maxLifeTime: 3600
    maxOpenConns: 100
    maxIdleConns: 10
oauth:
  github:
    provider: "GitHub"
    clientID: ""
    clientSecrets: ""
    redirectUrl: ""
redis:
  redis1:
    addr: 127.0.0.1:6379
    dbNo: 1